### ISSUE TITLE
Anchors and rpn module for varied image sizes (width!=height)

### ISSUE THREAD

**Issue by MLForNerds** [FurkanOM/tf-faster-rcnn#4]
Hi FurkanOM, Thanks for the great work!!
This repository works only for square images. What if i want to keep the aspect ratio of my images and train, like 1280x720. Then the anchor generation and anchor target generations have to be modified. Any thoughts on implementing this soon?

**Comment by FurkanOM** [comment]
Hi,
In fact, the anchor generation processes were working the way you specified at first, but I changed it later.
You can find the working version that way by examining the previous commits but I don't plan to implement that way.
Since the bounding boxes are in a relative format, the size or aspect ratios of the images do not pose any problem.

**Comment by MLForNerds** [comment]
Hi,
Thanks for the response. Can you point me the exact commit in which it is working that way. I can modify my code accordingly. Thanks.

**Comment by FurkanOM** [comment]
Hi, sorry but i couldn't. I'm dealing with other things right now. You need to find that by yourself.
