### ISSUE TITLE
  ValueError: The two structures don't have the same sequence length. Input structure has length 0, while shallow structure has length 9.

### ISSUE THREAD

**Issue by sabeeha1** [FurkanOM/tf-faster-rcnn#6]
Hello, Thanks Furqan for sharing your code. I am facing an issue while training the model with mobilenet_v2
![Screenshot from 2020-08-06 14-04-27](https://user-images.githubusercontent.com/48579101/89482582-4f3ff000-d7ee-11ea-9023-833581896f52.png)
![Screenshot from 2020-08-06 14-03-46](https://user-images.githubusercontent.com/48579101/89482465-143dbc80-d7ee-11ea-8ce0-871d2329834f.png)

other than that if I trace back, I find that image file's name are not being retrieved. as you can see from the first screen shot. snapshop. Even I cannot find where has tfds.load() downloaded the dataset. I cannot see that. can you please help.

**Comment by FurkanOM** [comment]
Hi,
Which tensorflow version are you using?

**Comment by sabeeha1** [comment]
Hi,

Thanks for your reply.

I am using 2.3.0 as 2.0.0 is not available anymore on tensorflow website.

**Comment by FurkanOM** [comment]
Hi,
The problem you encounter arises from the structure created when constructing the model.
This structure needs to be updated in versions above 2.0.
But since I am working on another subject now, unfortunately, I cannot update it.
If you want to use this repo, you must either make the necessary updates or use the tensorflow 2.0 version.
Also, no need to be on the website, you can install tensorflow 2.0 with pip or conda.
